### ISSUE TITLE
User profile with detailed data of user

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/tiwun-mobile#31]

**Comment by Alir3z4** [comment]
@amirm3hdi I'm working on the API to make querying the database for user data by its given `id`.

Full pagination and complete filtering supported as well.

**Comment by Alir3z4** [comment]
@amirm3hdi backend is ready to fire at, just pass the `user_id` to `index/` api endpoint and you have the user items only with all the features ;)

**Comment by Alir3z4** [comment]
@amirm3hdi Bump bump, when this one going to be done ?

**Comment by AmirSavand** [comment]
User profile is complete.
