### ISSUE TITLE
"Grunt serve" solution

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/tiwun-mobile#48]
I tried to run the server with Grunt serve, but it seems to be a broken link or a blank screen with an error that says " This webpage is not available " .
So searched a lot, finally I've found the solution to fix such error by downgrading grunt-concurrent .
( Steps to follow)
1. Uninstall grunt-concurrent by running the command -->`sudo npm uninstall grunt-concurrent`
2. Install grunt-concurrent by running the command --> `sudo npm install grunt-concurrent@1.0.0`

See if it works.

source --> https://github.com/diegonetto/generator-ionic/issues/223

**Comment by Alir3z4** [comment]
Hmm, nice.
lemme try it, @amirm3hdi killed himself for this.
I didn't have a time to stab at it, were just looking at it mostly.

Lemme give it a try on my local machine.

**Comment by AmirSavand** [comment]
Worked fine!

**Comment by Alir3z4** [comment]
Nice. Can one of you add the new version of the dependencies to the
packages.json file so the whole thing would work fine as well.
